### ISSUE TITLE
Define charter for Semantic Technologies Committee

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/stc#2]
Right now the Semantic Repository Implementation (SRI) Use Case and Requirements (UCR) document does not include our [Group Charter](https://esipfed.github.io/stc/UseCases/STCUseCasesAndRequirements.html#introduction) in the Introduction. We should agree upon a charter then augment the document to make a better case for the SRI based upon the STC charter.

**Comment by lewismc** [comment]
The STC is supposed to be a liaison between communities, both inside and outside of ESIPFed. There are a number of areas where the committee can help in integration of semantics within earth sciences and informatics relating to this field.

**Comment by rduerr** [comment]
Also, the charter needs to fit in with the ESIP Strategic Plan

**Comment by lewismc** [comment]
@rduerr do you have a link to the ESIP Strategic Plan which you can post here?

**Comment by lewismc** [comment]
Here it is 
http://wiki.esipfed.org/index.php/2015-2020_Strategic_Plan

**Comment by lewismc** [comment]
I've substantiated what the Deliverables are for the Group in https://esipfed.github.io/stc/UseCases/STCUseCasesAndRequirements.html#Deliverables
I feel that the charter is essentially represented at http://wiki.esipfed.org/index.php/Semantic_Technologies#2015-2020_Strategic_Plan_Goals
If this is not the case then someone please reopen this issue.
