### ISSUE TITLE
Requirements; section 5.1 -- 4D model of space-time

### ISSUE THREAD

**Issue by semantic-nomad** [ESIPFed/stc#7]
Does this need to be  a requirement?  Perhaps I'm taking a narrow view here, but the temporal commitment (or participation) of an ontology has to do with how the objects and/or processes are modeled, not how they are stored, versioned, etc., within the repository.

**Comment by lewismc** [comment]
Hi @brandonnodnarb this is garbage and has only been retained for the purpose of showing what a requirement would look like. We can and will remove it in due course. Thanks for pointing that out.

**Comment by semantic-nomad** [comment]
oh.  sorry.  that's twice I've done that now!
my bad.
/Brandon
